library(shiny)
library(ggplot2)
library(shinydashboard)
library(DT)

data <- read.csv(file = "./df.csv")

dashboardPage(
  
  #main title
  dashboardHeader(title="Dashboard"),
  dashboardSidebar(
    
    #sidebar
    sidebarMenu(
      menuItem("Home", tabName = "Home", icon = icon("home")),
      menuItem("Overview", tabName = "Info" ),
      menuItem("Analysis", tabName = "Charts", icon = icon("bar-chart-o"),selected=T,
               menuSubItem("Slide 1", tabName = "slide1"),
               menuSubItem("Slide 2", tabName = "slide2"),
               menuSubItem("Slide 3", tabName = "slide3"),
               menuSubItem("Slide 4", tabName = "slide4"),
               menuSubItem("Slide 5", tabName = "slide5"),
               menuSubItem("Slide 6", tabName = "slide6"),
               menuSubItem("Slide 7", tabName = "slide7"),
               menuSubItem("Slide 8", tabName = "slide8"),
               menuSubItem("Interactive Chart 1", tabName = "subitem1"),
               menuSubItem("Interactive Chart 2", tabName = "subitem2"),
               menuSubItem("Interactive Chart 3", tabName = "subitem3"),
               menuSubItem("Interactive Chart 4", tabName = "subitem4")),
      menuItem("Final Thoughts", tabName = "conclusion"),
      menuItem("About me", tabName = "about"),
      menuItem("Raw Data", tabName = "Data", icon = icon("table") )
    )

  ),
  #body of each tab
  body <- dashboardBody(
    tabItems(
      tabItem("Dashboard",div(p("Dashboard tab content"))),
      
      #Home tab (Background information)
      tabItem("Home",
              h1("Suicide & Mental Health Crisis"),
              h4("A deeper look of 51 countries and how suicides has trended from 2002-2015"),
              img(src = "mentalhealth.png", height = 500, width = 500),
              br(),
              br(),
              h3("What is Mental Health?"),
              a("MentalHealth.gov", href="https://www.mentalhealth.gov/basics/what-is-mental-health"),
              h5(HTML("'Mental health includes our emotional, psychological, and social well-being. It affects how we think, feel, and act. It also helps  <br/> determine how we handle stress, relate to others, and make choices. Mental health is important at every stage of life, from <br/> childhood and adolescence through adulthood.'")),
              h3("Why Mental Health?"),
              h5(HTML("Mental Health has in the past few years recently gained attention in the media here in the US.  It has greatly impacted atheletes, <br/> actors/actresses and many influencers. I wanted to take a closer look into the suicide rates worldwide to see what the numbers <br/> were saying.  This analysis will target suicides in 51 nations, 6 different age group, and 2 different gender categories")),
              h3("If you or anyone you know needs help:"),
              h5("National Institute of Mental Health:"),
              a("link", href="https://www.nimh.nih.gov/health/find-help"),
              h3("National Suicide Prevention Lifeline:"),
              h5("Call 1-800-273-TALK (8255)"),
              ),
      
      #Overview tab (Research Question/Business Need)
      tabItem("Info",
              h1("A Brief Introduction"),
              h4("Reasons for this analysis and the goals for this report"),
              h3("Target Audience:"),
              h5(HTML("Suicide is a multi-sector issue. It involves health care professionals, all branches of governments, politicians, and expands all the <br/> way to patients, caregivers and family members.  This also impacts any workplace and touches athletes or anyone dealing <br/> with pressures from social media.")),
              h3("Goals:"),
              h5(HTML("To spread awareness on Mental Health and to provide statistical insight on the topic.  This has recently come into the public's eye <br/> and not enough emphasis on cold hard facts have been stated.  'Is it an issue?', 'How bad is it?', 'Is it only within the US?'. <br/>  These are all valid questions and I hope to shed some answers with data to backup my reasoning.")),
              h3(HTML("<u>About the Data</u>")),
              h4("Dataset from Kaggle:"),
              img(src = "kaggle.png"),
              br(),
              a("Kaggle Dataset", href="https://www.kaggle.com/russellyates88/suicide-rates-overview-1985-to-2016"),
              h5(tags$li("Time Period = 1985-2016")),
              h5(tags$li("Data compiled by = World Bank, World Health Organization (WHO)")),
              img(src = "who.png"),
              br(),
              h4("Data Scrapping:"),
              h5(tags$li("Time Period shortened to 2002-2015")),
              h5(tags$li("Total of 51 countries")),
              h5(tags$li("Data split by gender (Male/Female)")),
              h5(tags$li("Data split by age group: (5-14), (15-24), (25-34), (35-54), (55-74), and (75+)")),
              br(),
              h4("Key Data Points:"),
              h5(tags$li("population: (population for that group)")),
              h5(tags$li("suicide_no: (the # of suicides for that group)")),
              h5(tags$li("gdp_per_year: (gdp for that year for the country)")),
              h5(tags$li("gdp_per_capita: (gdp per capita for that year for the country)")),
              ),
      
      # Charts tab (Analysis/Discussion/Results)
      tabItem("Charts"),
      
      tabItem("slide1",
              h3("First Look:"),
              br(),
              img(src = "graph1.png"),
              br(),
              h3("Global Suicides from 2002-2015:"),
              h4(tags$li("Decreasing trend")),
              h4(tags$li("Misleading chart")),
              h4(tags$li("Wide spread of data (see below)")),
              br(),
              img(src = "graph2.jpg", height = "75%", width = "75%"),
              ),
      tabItem("slide2",
              h3("Breakdown by Country:"),
              h4(tags$li("Europe & Central Asia concering")),
              h4(tags$li("South Korea, largest outlier for East Asian countries")),
              br(),
              img(src = "graph3.jpg"),
              ),
      tabItem("slide3",
              h3("Breakdown by Gender:"),
              br(),
              img(src = "graph4.jpg", height = "50%", width = "50%"),
              br(),
              br(),
              h4(tags$li(HTML("<b>1st Chart:</b> Gender split by Region"))),
              h4(tags$li(HTML("<b>2nt Chart:</b> Gender split by country"))),
              br(),
              img(src = "graph5.jpg", height = "75%", width = "75%"),
              ),
      tabItem("slide4",
              h3("Breakdown by Age Group:"),
              br(),
              img(src = "graph6.png", height = "50%", width = "50%"),
              br(),
              br(),
              h4(tags$li(HTML("<b>1st Chart:</b> Suicide by Age Group"))),
              h4(tags$li(HTML("<b>2nt Chart:</b> Age Group by Region"))),
              br(),
              img(src = "graph7.jpg", height = "60%", width = "60%"),
              ),
      tabItem("slide5",
              h3("This made me think..."),
              br(),
              h4(tags$li("What about if we evaluate generations?")),
              h4(tags$li("Silent Generation is prior to Boomers")),
              h4(tags$li("No concerning trend")),
              br(),
              img(src = "graph8.png"),
              ),
      tabItem("slide6",
              h3("What about when wealth factors in?"),
              br(),
              img(src = "graph11.png", height = "50%", width = "50%"),
              br(),
              br(),
              h4(tags$li(HTML("<b>1st Chart:</b> took yearly data and graphed every country"))),
              h4(tags$li(HTML("<b>2nt Chart:</b> same graph but tried to see it by region"))),
              br(),
              img(src = "graph12.png", height = "75%", width = "75%"),
              ),
      tabItem("slide7",
              h3("Let's try to find which countries have increasing rates of suicide"),
              br(),
              img(src = "graph9.png", height = "60%", width = "60%"),
              br(),
              br(),
              h4(tags$li("1st Failed attempt")),
              h4(tags$li("One year might have been favorable, the other might not have been")),
              h4(tags$li("Remember the high spread")),
              h4(tags$li("Correlation?")),
              br(),
              img(src = "chart1.jpg", height = "30%", width = "30%"),
              ),
      tabItem("slide8",
              h3("Correlation rate of # of suicides of all the years"),
              h4(tags$li("Brazil, US, Mexico, and Greece with the highest rates")),
              h4(tags$li("Will select US for further analysis")),
              br(),
              img(src = "graph10.jpg", height = "70%", width = "70%"),
              ),
      tabItem("subitem1",
              h3("Interactive Graph on Suicides by Country:"),
              br(),
              selectInput(inputId = "sel_country", label = "Choose Country", c(data$country), ),
              plotOutput("country_plot"),
              ),
      tabItem("subitem2",
              h3("Interactive Graph on # of Suicides vs GDP (per capita) by Country:"),
              br(),
              selectInput(inputId = "sel_gdp", label = "Choose Country", c(data$country) ),
              plotOutput("gdp_plot"),
              ),
      tabItem("subitem3",
              h3("Interactive Graph on Suicides (Age Groups) by Country:"),
              br(),
              selectInput(inputId = "sel_age", label = "Choose Country", c(data$country) ),
              plotOutput("age_plot"),
              ),
      tabItem("subitem4",
              h3("Interactive Graph on Suicides (Gender) by Country:"),
              br(),
              selectInput(inputId = "sel_gender", label = "Choose Country", c(data$country) ),
              plotOutput("gender_plot"),
                      
              
      ),

      # Conclusion tab (conclusion/future work/next steps)
      tabItem("conclusion",
              h2(HTML("<u>Final Thoughts</u>")),
              h4(tags$li("Conclusion")),
              h4(tags$li("Potential Problems")),
              h4(tags$li("Future Work/Next Steps")),
              img(src = "think.jpg"),
              h3("Conclusion:"),
              h5(tags$li("Globally, rates have been decreasing")),
              h5(tags$li("Growing concern in the United States")),
              h5(tags$li("Elderly Population has higher risk")),
              h5(tags$li("Males are more at risk vs Females")),
              br(),
              h3("Potential Problems:"),
              h5(tags$li("The need for more data")),
              h5(tags$li("Helping smaller & poorer countries to better track")),
              h5(tags$li("Data integrity")),
              br(),
              h3("Next steps:"),
              h5(tags$li("Bring in more individual factors")),
              h5(tags$li("Bring in more social/economic factors")),
              h5(tags$li("Predicing the future")),
      ),
            
      # About me tab
      tabItem("about",
              h2("About Me"),
              img(src = "profile.jpg", height = "19%", width = "19%"),
              h5(tags$li(HTML("<u>Name:</u>"))),
              h5("David Jhang"),
              h5(tags$li(HTML("<u>Location:</u>"))),
              h5("New York"),
              h5(tags$li(HTML("<u>Background:</u>"))),
              h5("Finance and Data Science"),
              h5(tags$li(HTML("<u>Social Media:</u>"))),
              a("LinkedIn", href="https://www.linkedin.com/in/djhang/"),
              br(),
              a("GitHub", href="https://github.com/djhang99/R-Data-Analysis-Project"),
              h5(tags$li(HTML("<u>Contact:</u>"))),
              a("Email Link", href="mailto:david.jhang@gmail.com"),
              h3(HTML("<U>Credits and Acknowledgement:</u>")),
              h5("Special thanks to the NYC Data Science Academy for making this analysis possible."),
              a("NYC Data Academy Link", href="https://nycdatascience.com/"),
              
              ),
      
      # Raw Data tab
      tabItem("Data",
              fluidPage(
                h2(HTML("<u>Raw Data Set (Suicide Rates from 2002-2005)</u>")),
                h5("(Data collected by the World Health Organization (WHO):"),
                img(src = "who.png"),
                br(),
                br(),
              dataTableOutput("datatable")                  
              )
    )
)
)
)
